internal_cidr: 10.0.0.0/26
internal_gw: 10.0.0.1
internal_ip: 10.0.0.40
network_name: drinks-chardonnay-pg
vcenter_cluster: drinks-cl
vcenter_dc: drinks-dc
vcenter_disks: pcf_operations_disks
vcenter_ds: wine-ds
vcenter_ip: 192.168.100.6
vcenter_templates: pcf_operations_templates
vcenter_vms: pcf_operations_vms

# flag: --dns
vcenter_dns: [ 8.8.4.4 ]

# flag: --resource-pool
vcenter_rp: chardonnay

# bosh cloud-config
minio_ip: 10.0.0.41
vcenter_datastore_names: [ 'wine-ds' ]
reserved_ip_ranges:
  - 10.0.0.1 - 10.0.0.6 # Gateway + OpsMan VM until BUCC (dont think there is a reason BUCC didnt use 10.0.0.3 but hey ho - update there is a Centos VM there leftover from network testing which Benoit said we can delete)
  - 10.0.0.15 - 10.0.0.29 # Based on CIDR /26 keep a load of IPs free for the target environments we want to rollout within the same network
  - 10.0.0.30 - 10.0.0.39 # OpsMan + PAS Small Footprint for testflight of PCF Operations Release
  - 10.0.0.45 - 10.0.0.49 # Based on CIDR /26 keep a load of IPs free for the target environments we want to rollout within the same network
  - 10.0.0.50 - 10.0.0.63 # Monitoring IPs

pcf_opsman_director_config_reserved_ip_ranges: 10.0.0.2-10.0.0.29,10.0.0.40-10.0.0.63

# Pivotal Platform Automation - config/opsman.yml
opsman_ip: 10.0.0.30
infra_ntp: 0.de.pool.ntp.org
testflight_opsman_hostname: pcf.testflight.dell-app.com
testflight_opsman_vm_name: Ops_Manager_TestFlight
vcenter_netmask: 255.255.255.0
vcenter_host_full_govc_path: /drinks-dc/host/drinks-cl/192.168.100.4
vcenter_vms_full_govc_path: /drinks-dc/vm/hz_automation_vms
vcenter_resource_pool_full_govc_path: /drinks-dc/host/drinks-cl/Resources/chardonnay
vcenter_ca_cert: |-
  -----BEGIN CERTIFICATE-----
  MIIEHTCCAwWgAwIBAgIJAMog3uTyyXvXMA0GCSqGSIb3DQEBCwUAMIGZMQswCQYD
  VQQDDAJDQTEXMBUGCgmSJomT8ixkARkWB3ZzcGhlcmUxFTATBgoJkiaJk/IsZAEZ
  FgVsb2NhbDELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExGzAZBgNV
  BAoMEmxvY2FsaG9zdC5sb2NhbGRvbTEbMBkGA1UECwwSVk13YXJlIEVuZ2luZWVy
  aW5nMB4XDTE3MTIxNjEzMDY1MFoXDTI3MTIxNDEzMDY1MFowgZkxCzAJBgNVBAMM
  AkNBMRcwFQYKCZImiZPyLGQBGRYHdnNwaGVyZTEVMBMGCgmSJomT8ixkARkWBWxv
  Y2FsMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEbMBkGA1UECgwS
  bG9jYWxob3N0LmxvY2FsZG9tMRswGQYDVQQLDBJWTXdhcmUgRW5naW5lZXJpbmcw
  ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC97TfVvzmPrrpMuoVyMSI1
  XZ7pXeHqC9Zqp2XmNpwzE+RyWgvlwHbqBAzD+M2owakD5urip510eljph/nADiLY
  L3q9oOK9Bg44IYDUNBp+ad0C3aqXV13SbhE0t0SeUrcGpUGhBIwQEueDH2dSkYkt
  xZBPxPQHbV9dnsoalS9muwXXxVkEZP/JqBYNBNAFQeSjAlK138/WwmgXMVKlJEYs
  R4igmKdd4B3rqp8mLUpIqx+pq3DI+shLoCfpoMoJcD/wwGxokiLgsM4dJHk+1Fgd
  Z6fmaCRzEMQ0n533DZf7h7rEA1BqCrGd3ANdTZi2gK8S9hudrVdQ5pnQXQo2oX3z
  AgMBAAGjZjBkMB0GA1UdDgQWBBSKZmcxYnocT3aQPPTRVh8607wnEjAfBgNVHREE
  GDAWgQ5lbWFpbEBhY21lLmNvbYcEfwAAATAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0T
  AQH/BAgwBgEB/wIBADANBgkqhkiG9w0BAQsFAAOCAQEAgz+PuOEC2UmG2b834oRX
  90yI6G8YEHOrFTZhXXDGVEX9Ug8XhPYMgsj0eRb0sdj+LjUwWqte92ZLjST+t/1T
  gd7XEGShwbFWuduQOLjWwptljGRD2W5GqBH353waxxc4bSPj16+2f22uo5mFpUp0
  /V5NWDXIFLAtchWJKODlDOR7Kump+Zxf87PpOUtbKOlrl7R6v0edSA0VS4RF7ZQL
  kkqKhTD0k49vvK6p7esBiiysEj8/1mV47IB0x4gXg/VVXxPbU2TQl8LGGLcakfRZ
  +Yfkl258640PEmjPRuOrFUvwa41E8q5KlN+HaQ6SlLf0Mpn3XNf5OJeuQjUsttNe
  cg==
  -----END CERTIFICATE-----
